spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news_web?useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/static/pages/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
